development:
  adapter: 'postgresql'
  database: 'bairdconklinmath_dev'
  pool: 5
  timeout: 5000

test:
  adapter: 'postgresql'
  database: 'bairdconklinmath_test'
  pool: 5
  timeout: 5000

production:
  adapter: 'postgresql'
  database: 'bairdconklinmath'
  host: 'localhost'
  pool: 5
  timeout: 5000
