development:
  adapter: 'postgresql'
  database: 'bairdconklinmath_devevelopment'
  pool: 5
  timeout: 5000

test:
  adapter: 'postgresql'
  database: 'bairdconklinmath_test'
  pool: 5
  timeout: 5000

production:
  adapter: 'postgresql'
  database: 'bairdconklinmath_productin'
  pool: 5
  timeout: 5000
