# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61d1a8da8d4e6a8fa572f9364bca4a0b9de03fa8590cc6301d6b1e8122b5c0343788b7f3703702ea9b7f56203223bc4349299e208d7ec66808e52c119c1525a9

test:
  secret_key_base: 6332de90de552151a083eb3446359b7e839c92270cec4236f12a0118cb97a04a25a893a32215b81d6aebcd164fbea2230f4504c4b59d0c902fe1dbed42a80405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
